### ISSUE TITLE
Battery draining too quickly

### ISSUE THREAD

**Issue by abhidiwakar** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh#10]
After installing macOS 10.15.4, everything now seems to be working fine but I think that battery is draining too quickly and also maybe getting damaged somehow. I use my laptop Asus X510 UNR for Android and Web Development (Mostly Android) and the battery lasts about less than an hour on a single charge. I have to keep my laptop connected to a power source for uninterrupted workflow. Honestly, I don't mind keeping my laptop connected to a power source but recently I noticed something that made me submit this issue.

![Screenshot 2020-04-29 at 3 29 22 AM](https://user-images.githubusercontent.com/39366969/80542460-9e45e000-89ca-11ea-8459-36aa040b8b46.png)

As you can see in the screenshot above, this warning wasn't there when I installed macOS. It appeared recently and made me worried about my laptop. Is this a serious issue? Is there any solution for this?

**Side note**: I don't keep my laptop connected to a power source all the time. I connect it only when the battery level reaches below 10% and I remove it as soon as it reaches 100%.

**Comment by whatnameisit** [comment]
Is this issue new in 10.15.4?
By user experience, the battery management is different for macOS and Windows.
Here's what you could do:
1. Let the laptop run with power connected for an hour.
2. Disable XCPM (SSDT-PLUG.aml) to see if the reading becomes any different.
Aside that, please post your patchmatic ACPI here. FBST may need to be patched.

**Comment by abhidiwakar** [comment]
Honestly speaking, I'm new to all this stuff and I don't really know where to find patchmatic ACPI. Can you link me with an instruction article that can help me to get that patchmatic ACPI?

**Comment by whatnameisit** [comment]
Google patchmatic and download the binary from github.
This is the command you type into the terminal: 
cd ~/Desktop
mkdir extract
cd extract
patchmatic -extract

**Comment by abhidiwakar** [comment]
After running pathcmatic -extract, I got 24 files which I've attached below in a zip file. Please have a look. Thanks in advance. 🙏🏼

[Extracted.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4551807/Extracted.zip)

**Comment by whatnameisit** [comment]
Your battery code is no different than mine.
Let the laptop run on power for an hour and see if that fixes the issue.

**Comment by vasishath** [comment]
> After running pathcmatic -extract, I got 24 files which I've attached below in a zip file. Please have a look. Thanks in advance. 🙏🏼
> 
> [Extracted.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4551807/Extracted.zip)

You have disabled the nvidia GPU right ?

**Comment by abhidiwakar** [comment]
> > After running pathcmatic -extract, I got 24 files which I've attached below in a zip file. Please have a look. Thanks in advance. 🙏🏼
> > [Extracted.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4551807/Extracted.zip)
> 
> You have disabled the nvidia GPU right ?

I have simply copied open core folder from this repo into my efi. Also I've made some changes in config.plist to enable keyboard backlit. I haven't done anything else.

**Comment by vasishath** [comment]
> > > After running pathcmatic -extract, I got 24 files which I've attached below in a zip file. Please have a look. Thanks in advance. 🙏🏼
> > > [Extracted.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4551807/Extracted.zip)
> > 
> > 
> > You have disabled the nvidia GPU right ?
> 
> I have simply copied open core folder from this repo into my efi. Also I've made some changes in config.plist to enable keyboard backlit. I haven't done anything else.

Add -wegnoepgu to ur boot args to disable nvidia GPU. That should save significant amount of power.

**Comment by dayfly** [comment]
I use open core and battery for about an hour. S510UNR i7-8550U.

**Comment by whatnameisit** [comment]
> Your battery code is no different than mine.
> Let the laptop run on power for an hour and see if that fixes the issue.
> 
> Edit
> Take a screenshot of System Profiler-Power and post it here please.

@abhidiwakar Report please.
@dayfly 전원 연결하고 한 시간 놔두고 나서 테스트해보세요. 충전 제거하고 10%까지 몇 시간 걸리는지 알려주세요.

**Comment by dayfly** [comment]
@whatnameisit 한시간 반 정도 나옵니다

**Comment by whatnameisit** [comment]
Show your System Profiler's battery capacity at 100%, and then start the count, please.
시스템 리포트에서 100%일 때의 배터리 용량 스크린샷으로 올려주세요. 그리고 나서 몇 시간 걸리는지 재보세요. 간단한 브라우저 사용만 하는 중에서요.

**Comment by dayfly** [comment]
![스크린샷 2020-05-05 오후 12 57 24](https://user-images.githubusercontent.com/8287834/81035502-3580cb00-8ed6-11ea-86f1-ce632f20da57.png)
시간당 배터리가 20퍼 빠집니다 10퍼 될 떄 까지요

**Comment by whatnameisit** [comment]
네 문제 없으시네요.
Confirmed same discharging rate among the X510U models.

**Comment by dayfly** [comment]
마지막으로 질문 하나만 해도될까요? CPUFriendDataProvider.kext 이거를 맥북 에어 8.2로 바꾸었는데 smbios모델로 같이 바꾸어야 하나요>?

**Comment by whatnameisit** [comment]
@dayfly README에 없는 내용입니다. 제 가이드와 상관 없는 질문이에요. 이 Issue와도 상관 없는 질문이에요. 그리고 Github 사용취지에 알맞지도 않습니다.
가이드와 상관 있는 질문이란 "CPUFriendDataProvider.kext 어떻게 사용하는건가요/다른 것으로 교체해보고 싶습니다." 정도 입니다.
이 Issue와 상관 있는 것이란 "배터리 방전 관련해서 여러 가지 시도해보고 싶었기 때문에 CPUFriendDataProvider.kext를 바꾸어 보았습니다." 정도 입니다.
Github 사용취지에 알맞는 것이란 "다른 CPUFriendDataProvider.kext를 사용했을 때 이런 저런 점이 있습니다." 정도 입니다.
그리고 질문하실 때 위의 관련성과 사용취지와 상관 없이 정확한 답변을 원하시면 정확한 데이터를 제공해주세요.
무슨 이유로 CPUFriendDataProvider.kext를 바꾸셨는지.
어디서 이 켁스트를 구하셨는지.
CPUFriend 사용법 읽어보셨는지.
여기 제공되는 CPUFriendDataProvider.kext가 맥북 에어 8.2라고 생각해 보셨는지.
지금 사용중에 발생하는 현상/문제점/장점이 무엇인지.
원하는 질문 딱 던져 놓고 될 대로 되라 하시면 피곤합니다. 제가 "될 대로 되라"라고 생각하는 근거는 질문에 오타를 수정할 시도도 안 했다는 점이죠.

> 마지막으로 질문 하나만 해도될까요? CPUFriendDataProvider.kext 이거를 맥북 에어 8.2로 바꾸었는데 smbios모델로 같이 바꾸어야 하나요****>****?

충분히 고려하신 후 관련 있는 내용으로 질문해주세요.
