### ISSUE TITLE
Intel Wifi kext kernel panic 

### ISSUE THREAD

**Issue by abidshahriar** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh#11]
I was using intelwifi.kext..However when i load the kext i get a panic. I was using you clatest clover folder. In system report i had seen other wifi drivers.in acpi >patched i was looking for the wifi fix that causing issue here .please let me know what to do deleting the wifi configuration you implemented in your clover. Thanks

**Comment by abidshahriar** [comment]
![942EB459-FF05-4653-B343-36F1E7A8D332](https://user-images.githubusercontent.com/64680295/83189284-d0299e00-a152-11ea-817b-9612984e7e41.jpeg)
![53423926-7DC9-4D81-AF27-7E79DBB4DAAE](https://user-images.githubusercontent.com/64680295/83189295-d750ac00-a152-11ea-9bdb-1decf42ce6a8.jpeg)

**Comment by whatnameisit** [comment]
Provide full details on the said loaded wifi kexts in System Profiler and read README on the wifi part. The issue is not mine, but misconfiguration or the Intel kext's fault.
