### ISSUE TITLE
Feature Enhancement for Asus X510 UNR

### ISSUE THREAD

**Issue by abhidiwakar** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh#7]
I used OpenCore from this repo for my Asus X510UNR. It is working super fine. I actually didn't expect it to work like this. Everything seems to be working fine but the only problem I have is keyboard backlit. I'm unable to turn on the keyboard backlit. Can you please get it working?

**Comment by whatnameisit** [comment]
It's great to hear that someone benefits from it :)
As for the issue you reported, it is mentioned in the README. My laptop does not have the keyboard backlight feature, and if you would like yours to have it working, you need to go to tctien342's or hieplpvip's repo. And that's Clover.
But I can come up with a fix in accordance with how my OpenCore setup works later today. If you are in a hurry, look into my fork of hieplpvip's Asus-zenbook-hackintosh repo in src/hotpatch/include/SSDT-ATK-KABY.dsl. Be careful not to have duplicate _Qxx entries.
Also test if the internal mic works. If it doesn't, boot into recovery, disable sip, boot into mac, install CodecCommander to /L/E, boot into recovery, enable sip, boot into mac, and see if it works.

**Comment by vasishath** [comment]
I have the same laptop but i get this early kernel panic when using OpenCore on catalina 10.15.3. 

`panic(cpu 4 caller 0xffffff80004652fa): Kernel trap at 0xffffff7f836537a0, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff7f836537a0, CR3: 0x0000000005a04000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff8014937e00, RCX: 0x00000000000a000b, RDX: 0xffffff7f8387eabf
RSP: 0xffffff8103fa3db8, RBP: 0xffffff8103fa3de0, RSI: 0xffffff7f8387eab4, RDI: 0xffffff7f8387ea8d
R8:  0x0000000000000001, R9:  0x000000000000000b, R10: 0x000000807fffefff, R11: 0x0000000000000010
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0xffffff80148efec0, R15: 0xffffff80148efec0
RFL: 0x0000000000210246, RIP: 0xffffff7f836537a0, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff7f836537a0, Error code: 0x0000000000000010, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffff8103fa3810 : 0xffffff800033bb2b mach_kernel : _handle_debugger_trap + 0x47b
0xffffff8103fa3860 : 0xffffff80004734d5 mach_kernel : _kdp_i386_trap + 0x155
0xffffff8103fa38a0 : 0xffffff8000464f4e mach_kernel : _kernel_trap + 0x4ee
0xffffff8103fa38f0 : 0xffffff80002e2a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8103fa3910 : 0xffffff800033b217 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff8103fa3a10 : 0xffffff800033b5fb mach_kernel : _panic_trap_to_debugger + 0x21b
0xffffff8103fa3a60 : 0xffffff8000ad2aa9 mach_kernel : _panic + 0x61
0xffffff8103fa3ad0 : 0xffffff80004652fa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff8103fa3c50 : 0xffffff8000464ff8 mach_kernel : _kernel_trap + 0x598
0xffffff8103fa3ca0 : 0xffffff80002e2a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8103fa3cc0 : 0xffffff7f836537a0 
0xffffff8103fa3de0 : 0xffffff8000a1b216 mach_kernel : __ZN9IOService14startCandidateEPS_ + 0xf6
0xffffff8103fa3e40 : 0xffffff8000a1adc1 mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xb21
0xffffff8103fa3ef0 : 0xffffff8000a1a10e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2ce
0xffffff8103fa3f50 : 0xffffff8000a1c8ad mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x15d
0xffffff8103fa3fa0 : 0xffffff80002e213e mach_kernel : _call_continuation + 0x2e

BSD process name corresponding to current thread: Unknown
Boot args: -v keepsyms=1

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Kernel UUID: A8DDE75C-CD97-3C37-B35D-1070CC50D2CE
__HIB  text base: 0xffffff8000100000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 1985931883


`

I am using clover currently to boot macos.

**Comment by whatnameisit** [comment]
@vasishath open a separate issue because your problem had nothing to do with keyboard backlight.

**Comment by abhidiwakar** [comment]
> It's great to hear that someone benefits from it :)
> As for the issue you reported, it is mentioned in the README. My laptop does not have the keyboard backlight feature, and if you would like yours to have it working, you need to go to tctien342's or hieplpvip's repo. And that's Clover.
> But I can come up with a fix in accordance with how my OpenCore setup works later today. If you are in a hurry, look into my fork of hieplpvip's Asus-zenbook-hackintosh repo in src/hotpatch/include/SSDT-ATK-KABY.dsl. Be careful not to have duplicate _Qxx entries.
> Also test if the internal mic works. If it doesn't, boot into recovery, disable sip, boot into mac, install CodecCommander to /L/E, boot into recovery, enable sip, boot into mac, and see if it works.
> 
> Edit
> Try this: https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh/blob/master/Clover%20EFI/EFI/CLOVER/ACPI/additional/SSDT-ATK-KABY-bkl.aml
> You need to add it inside config.plist/ACPI/ADD. Look at other added SSDTs for reference. Please report back if it works OK.

I'm using open core. I copied this aml file to the ACPI folder and then I added the same in config.plist but the keyboard backlit didn't work.

**Comment by whatnameisit** [comment]
Please try this.
[SSDT-ATK-KABY-bkl.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4532732/SSDT-ATK-KABY-bkl.zip)
Use this one if the above doesn't work.
[SSDT-ATK-KABY2.aml.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4532739/SSDT-ATK-KABY2.aml.zip)
And please report back.

**Comment by abhidiwakar** [comment]
> Please try this.
> [SSDT-ATK-KABY-bkl.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4532732/SSDT-ATK-KABY-bkl.zip)
> Use this one if the above doesn't work.
> [SSDT-ATK-KABY2.aml.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4532739/SSDT-ATK-KABY2.aml.zip)
> And please report back.


Thanks, dude. This worked for me.
[SSDT-ATK-KABY-bkl.zip](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/files/4532732/SSDT-ATK-KABY-bkl.zip)

Keyboard backlit is now working as expected.
