### ISSUE TITLE
X510UNR wakes up instantly after sleep only when battery is low

### ISSUE THREAD

**Issue by vasishath** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh#9]
When I try to put the system to sleep during low battery, it wakes up after 2-3 seconds in sleep. The pmset log shows:-

Wake from Normal Sleep [CDNVA] : due to PWRB/User Using BATT (Charge: 0%)

No external devices are connected to the system at this point.

Sleep otherwise works normally but this thing occurs only when battery is low.

Additionally, the system doesn't auto sleep or Hibernate (I tried enabling hibernation also) when battery is low.

Is this familiar ?

**Comment by whatnameisit** [comment]
Battery: Try one of the scripts found here: https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/tree/master/post%20macOS%20Installations/%5BOptional%5D/SleepOnLowBattery%20(SOLB)
Hibernation: I used Hackintool's power fix to disable hibernation and other properties that are said to be unsupported on hackintosh. They might work since the Acidanthera team released HibernationFixup and the corresponding settings in OpenCore, but many OpenCore guides disapproves it and even the official configuration.pdf says "Disable hibernation for your own good." I have tried hibernation, but it didn't work. I have not seen a guide to actually implement hibernation, or revert from the disabled settings to hibernate compatible settings other than installing HibernationFixup, so I don't know what to do. At least it's pmset hibernatemode 25(real hibernation), pmset standby 1(settings required for the latest commits in HibernationFixup), and OpenCore's HibernateMode to NVRAM.

**Comment by vasishath** [comment]
> Battery: Try one of the scripts found here: https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/tree/master/post%20macOS%20Installations/%5BOptional%5D/SleepOnLowBattery%20(SOLB)
> Hibernation: I used Hackintool's power fix to disable hibernation and other properties that are said to be unsupported on hackintosh. They might work since the Acidanthera team released HibernationFixup and the corresponding settings in OpenCore, but many OpenCore guides disapproves it and even the official configuration.pdf says "Disable hibernation for your own good." I have tried hibernation, but it didn't work. I have not seen a guide to actually implement hibernation, or revert from the disabled settings to hibernate compatible settings other than installing HibernationFixup, so I don't know what to do. At least it's pmset hibernatemode 25(real hibernation), pmset standby 1(settings required for the latest commits in HibernationFixup), and OpenCore's HibernateMode to NVRAM.

Yes, I am already using the script u mentioned but it still wakes up on its own after 2-3 seconds. Infact, I even tried removing the script, suspecting that it maybe the one causing the wakeups lol. Actually, what I have observed is, if I set Hibernate to 3, I get a kernel panic when I try to sleep the system for the second time (only when battery is low). But if I set it to 25, then it doesn't panic.
I enabled hibernation because I thought maybe the system tries to wakeup to Hibernate itself but that's not the case either. So, why is the wakeup happening ?

**Comment by whatnameisit** [comment]
What are your energy related settings in the "Settings app?" At what percentage is the sleep issue occurring?

**Comment by vasishath** [comment]
> What are your energy related settings in the "Settings app?" At what percentage is the sleep issue occurring?

Following are my energy settings:-

`Currently in use:
 standby              0
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 powernap             0
 gpuswitch            0
 disksleep            10
 standbydelayhigh     86400
 sleep                10
 hibernatemode        0
 ttyskeepawake        1
 displaysleep         2
 highstandbythreshold 50
 standbydelaylow      10800
`

And this issue starts at 5% battery level.

**Comment by whatnameisit** [comment]
I meant to ask for the Energy Saver pane in Settings app. Please uncheck everything except "Put hard disks to sleep when possible" and see if that made a change.

**Comment by vasishath** [comment]
Oh. Here is my Energy Saver pane. I will try disabling the dim display option to check.

![Screen Shot 2020-04-27 at 10 54 22 AM](https://user-images.githubusercontent.com/6087015/80336903-1fd82980-8876-11ea-8dd5-b32d6429d11b.png)

**Comment by whatnameisit** [comment]
I have no problem with my Vivobook's sleep and wake. Draining the battery as low as 5 % isn't good for its health. Feed it some more electricity and you have no problem.
Also look up critical battery wake. I've come to believe this is implemented in Vivobook's UEFI BIOS.

**Comment by whatnameisit** [comment]
Test sleep at 5 percent battery via ACPI https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Hackintosh/tree/batterylow
Test sleep at 5 percent battery via kernel https://github.com/acidanthera/HibernationFixup/actions/runs/1245916539
